  name: "my_action"

  description: "my action"
  runs:
    using: "composite"
    steps:
      - run: poetry run pytest -vv
        shell: bash
      - run: poetry run flake8 gendiff
        shell: bash
      - name: Test & publish code coverage
        uses: paambaati/codeclimate-action@v3.2.0
        if: github.ref_name == 'main'
        with:
          CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}
          coverageCommand: make test-coverage
          debug: true