
name: "my_test"

on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          pip install poetry
          make install
      - name: Testing
        run: |
          poetry run pytest -vv
          poetry run flake8 gendiff
#      - name: Test & publish code coverage
#        uses: paambaati/codeclimate-action@v3.2.0
#        if: github.ref_name == 'main'
#        env:
#          CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}
#        with:
#          coverageCommand: make test-coverage
#          debug: true
